### ISSUE TITLE
Example failing

### ISSUE THREAD

**Issue by gregc-91** [osanj/lava#23]
Hi,
After installing on Windows 10, the example fails for me during buffer allocation with the following:

```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    buffer_out = lv.StagedBuffer.from_shader(session, shader, binding=0)
  File "C:\Users\Greg\AppData\Roaming\Python\Python38\site-packages\lava\buffer.py", line 208, in from_shader
    return cls(session, block_definition, block_usage, sync_mode)
  File "C:\Users\Greg\AppData\Roaming\Python\Python38\site-packages\lava\buffer.py", line 195, in __init__
    self.buffer_cpu = BufferCPU(session, block_definition, block_usage, sync_mode)
  File "C:\Users\Greg\AppData\Roaming\Python\Python38\site-packages\lava\buffer.py", line 112, in __init__
    super(BufferCPU, self).__init__(session, block_definition, block_usage, Buffer.LOCATION_CPU)
  File "C:\Users\Greg\AppData\Roaming\Python\Python38\site-packages\lava\buffer.py", line 78, in __init__
    self.allocate()
  File "C:\Users\Greg\AppData\Roaming\Python\Python38\site-packages\lava\buffer.py", line 95, in allocate
    self.vulkan_memory = self.session.device.allocate_memory(memory_types, minimum_size, supported_memory_indices)
  File "C:\Users\Greg\AppData\Roaming\Python\Python38\site-packages\lava\api\device.py", line 162, in allocate_memory
    raise RuntimeError("Could not find a device memory which supports {}".format(" and ".join(memory_types)))
RuntimeError: Could not find a device memory which supports HOST_COHERENT and HOST_VISIBLE
```

My device list is length 1, with the following entry which seems to support the requested memory types:
```
device_name: GeForce GTX 1070 Ti
device_type: DISCRETE_CPU
handle: <cdata 'struct VkPhysicalDevice_T *' 0x0BEB8470>
heap_sizes: {1: 8555696128, 0: 8472494080}
memory_type_idx: {'DEVICE_LOCAL': [7, 8], 'HOST_VISIBLE': [9, 10], 'HOST_COHERENT': [9, 10], 'HOST_CACHED': [10], 'LAZILY_ALLOCATED': []}
memory_type_idx_to_heap: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 0, 8: 0, 9: 1, 10: 1}
queue_idx: {'GRAPHICS': [0], 'COMPUTE': [0, 2], 'TRANSFER': [0, 1], 'SPARSE_BINDING': [0]}
queue_support: {'GRAPHICS': True, 'COMPUTE': True, 'TRANSFER': True, 'SPARSE_BINDING': True}
uniform_max_bytes: 65536
work_group_max_counts: [2147483647, 65535, 65535]
work_group_max_invocations: 1536
work_group_max_sizes: [1536, 1024, 64]
```

If you are still supporting this, any chance you can help me figure out why StagedBuffer.from_shader() is failing?

**Comment by osanj** [comment]
Can you step through the following passage with a debugger?
https://github.com/osanj/lava/blob/13c234eb8a10e047646b07f2aba43ee80afcd81e/lava/api/device.py#L73-L88

If you can not do that, you can also add print statements:
* either in your site-package directly (you should probably undo it later)
* or clone the repository, `git checkout 0.3.2` (or whatever version you are using) and `pip install -e /path/to/my/lava/repo`

---

My expectation is that `indices` (at the end of this method) should at least contain `[9, 10]` based on the second part your post. However it seems to be empty, that's what raises the exception. Can you share what values ~`memory_types`~ (we know that already 😬), `supported_memory_indices` and `self.memory_type_idx` have during debugging?

**Comment by gregc-91** [comment]
`indices` is empty
`supported_memory_indices` is empty
`memory_type_idx` is:
{'DEVICE_LOCAL': [7, 8], 'HOST_VISIBLE': [9, 10], 'HOST_COHERENT': [9, 10], 'HOST_CACHED': [10], 'LAZILY_ALLOCATED': []}

The supported memory indices being empty originates from the Vulkan call
`vkGetBufferMemoryRequirements` in `Buffer::get_memory_requirements()`,
which has no bits set in the `requirements.memoryTypeBits`

The inputs are just handles, not sure if those structs are opaque or not
```
<cdata 'struct VkDevice_T *' 0x105E4708>
<cdata 'struct VkBuffer_T *' 0x00A7FC10>
```

It's looking like it might be something outside of your control.

Do you know if different Vulkan versions change the struct layouts? I have a few installed on my system but my path should be setup for 1.1.108, which was as close as I could find to 1.1.99.1

**Comment by osanj** [comment]
> I have a few installed on my system but my path should be setup for 1.1.108, which was as close as I could find to 1.1.99.1

~Where did you find 1.1.108? On [pypi](https://pypi.org/project/vulkan/#history) and [GitHub](https://github.com/realitix/vulkan/releases) I can only find versions up to 1.1.99.1.~ Nevermind

> Do you know if different Vulkan versions change the struct layouts?

Seems like there was no change
https://github.com/KhronosGroup/Vulkan-Headers/compare/sdk-1.1.92.0..sdk-1.1.108#diff-4febd94c0666d59030d8b1dd20c72403
https://github.com/KhronosGroup/Vulkan-Headers/blob/sdk-1.1.92/include/vulkan/vulkan_core.h#L2090-L2094
https://github.com/KhronosGroup/Vulkan-Headers/blob/sdk-1.1.108/include/vulkan/vulkan_core.h#L2149-L2153

Another option might be that the GPU driver that you have currently installed, somehow does not have this part of the vulkan specification (properly) implemented. The only way to find this out is to try a bunch of different versions, though.

**Comment by gregc-91** [comment]
Yeah so as I understand it the driver implements the runtime, the SDK provides the headers, the python binding directly wraps them, and lava abstracts the details.

The python binding library is 1.1.99.1, but hasn't been updated in months. I assumed the versioning corresponds to the Vulkan SDK it's calling, which is why I tried to avoid using a modern version.

I can run the Vulkan example this is based on (with no python interaction), so my SDK and Driver work fine standalone.
[Erkaman's vulkan minimal compute](https://github.com/Erkaman/vulkan_minimal_compute)

I'll test some things out and get back to you. Thanks for the help.

**Comment by gregc-91** [comment]
It looks like this is an issue with the Python Vulkan binding module. I can't get their examples to work on two different machines.

Since I believe this isn't related to Lava I'm closing this.
Thanks
